### ISSUE TITLE
Does not work with local install

### ISSUE THREAD

**Issue by amacleay** [jondot/hygen-add#1]
... but you probably already know that. It would be a nice feature.

To reproduce:
```sh
cd `mktemp -d`
yes "" | npm init
npm i -D hygen-add yarn
npx hygen-add cra
```
Result:
```
$ npx hygen-add cra
⠋ Adding: hygen-cra

Can't add hygen-cra

 { Error: Command failed: /bin/sh -c /tmp/tmp.4Xhq6XS3hA/node_modules/hygen-add/node_modules/.bin/yarn add --dev hygen-cra
/bin/sh: 1: /tmp/tmp.4Xhq6XS3hA/node_modules/hygen-add/node_modules/.bin/yarn: not found


    at makeError (/tmp/tmp.4Xhq6XS3hA/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/tmp/tmp.4Xhq6XS3hA/node_modules/execa/index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 127,
  stdout: '',
  stderr: '/bin/sh: 1: /tmp/tmp.4Xhq6XS3hA/node_modules/hygen-add/node_modules/.bin/yarn: not found\n',
  failed: true,
  signal: null,
  cmd: '/bin/sh -c /tmp/tmp.4Xhq6XS3hA/node_modules/hygen-add/node_modules/.bin/yarn add --dev hygen-cra',
  timedOut: false,
  killed: false }
⠋ Adding: hygen-cra^C
```
(Spins and has to be killed because of unhandled promise rejection)

Possible solution: use [npx](https://www.npmjs.com/package/libnpx) or something similar to get the executable.

**Comment by nickguimond** [comment]
A local install would allow me to use this in an electron app as a widget code creator ... Is is possible to get this working locally?
